### ISSUE TITLE
Show Admin/Teacher Panel

### ISSUE THREAD

**Issue by wnicolaas** [WesleyKlop/ipsen5#65]
**Epic:** Show Admin/Teacher Panel

**Task:** Admins or Teachers should be able to see a panel where they can start or edit surveys (and more)

- [ ] Custom survey screen (also accessible in trial version)
- [ ] National related survey screen
- [ ] Europe related survey screen

> _Happy programming_
